#!/usr/bin/env bash
# Generate release notes from the commit log (conventional commits).
#
# Commits are grouped by type (breaking changes first, then feat, fix, perf,
# refactor, everything else). tools/release.sh uses this same script for its
# annotated tag messages, so there is exactly one notes generator.
#
# Usage:
#   tools/changelog.sh                     latest tag..HEAD
#   tools/changelog.sh <from> [<to>]       any refs (tags, shas, HEAD)
#   tools/changelog.sh --write [...]       prepend the section to CHANGELOG.md
#
# Examples:
#   tools/changelog.sh                     notes since the last tag
#   tools/changelog.sh v1.0.0 v1.1.0       notes for a released range
#   tools/changelog.sh --write             prepend HEAD notes to CHANGELOG.md

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

WRITE=0
REFS=()
for arg in "$@"; do
    case "$arg" in
        --write) WRITE=1 ;;
        -h | --help)
            sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) REFS+=("$arg") ;;
    esac
done

FROM="${REFS[0]:-}"
TO="${REFS[1]:-HEAD}"

# A ref that does not exist is almost certainly a typo -- fail loudly
# instead of emitting an empty changelog.
for ref in "$FROM" "$TO"; do
    if [ -n "$ref" ] && ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$ref" >/dev/null; then
        die "no such ref: $ref"
    fi
done

if [ -z "$FROM" ]; then
    FROM="$(git -C "$REPO_ROOT" describe --tags --abbrev=0 2>/dev/null || true)"
    if [ -n "$FROM" ]; then
        note "No <from> given -- using latest tag: $FROM"
    else
        note "No tags exist yet -- generating from the start of history"
    fi
fi

# -- resolve title, date, compare link ----------------------------------------

TITLE="$(git -C "$REPO_ROOT" describe --tags --exact-match "$TO" 2>/dev/null || true)"
if [ -z "$TITLE" ]; then
    TITLE="Unreleased"
    DATE="$(date +%Y-%m-%d)"
else
    DATE="$(git -C "$REPO_ROOT" log -1 --format=%as "$TO")"
fi

REMOTE="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || true)"
REMOTE="${REMOTE#git@github.com:}"
REMOTE="${REMOTE#https://github.com/}"
REMOTE="${REMOTE%.git}"
COMPARE=""
if [ -n "$FROM" ] && [ -n "$REMOTE" ]; then
    COMPARE="https://github.com/$REMOTE/compare/$FROM...$TO"
fi

# -- generate the markdown -----------------------------------------------------

if [ -n "$FROM" ]; then
    LOG_RANGE="$FROM..$TO"
else
    LOG_RANGE="$TO"
fi

RAW="$(git -C "$REPO_ROOT" log --no-merges --format='%s' "$LOG_RANGE")"
if [ -z "$RAW" ]; then
    die "no commits in range $LOG_RANGE"
fi

BODY="$(printf '%s\n' "$RAW" | bun -e '
const chunks = [];
for await (const chunk of process.stdin) chunks.push(chunk);
const lines = Buffer.concat(chunks).toString().split("\n").filter(Boolean);

const parse = (subject) => {
    const m = subject.match(/^([a-z]+)(?:\(([^)]+)\))?(!)?:\s+(.*)$/);
    if (!m) return { type: null, scope: null, breaking: /BREAKING CHANGE/i.test(subject), subject };
    return {
        type: m[1],
        scope: m[2] || null,
        breaking: m[3] === "!" || /BREAKING CHANGE/i.test(subject),
        subject: m[4],
    };
};

const commits = lines.map(parse);
const used = new Set();
const emit = (title, group) => {
    const fresh = group.filter((c) => !used.has(c));
    if (fresh.length === 0) return "";
    for (const c of fresh) used.add(c);
    const items = fresh
        .map((c) => (c.scope ? `- **${c.scope}:** ${c.subject}` : `- ${c.subject}`))
        .join("\n");
    return `### ${title}\n\n${items}\n\n`;
};

let out = "";
out += emit("Breaking changes", commits.filter((c) => c.breaking));
out += emit("Features", commits.filter((c) => c.type === "feat"));
out += emit("Fixes", commits.filter((c) => c.type === "fix"));
out += emit("Performance", commits.filter((c) => c.type === "perf"));
out += emit("Refactoring", commits.filter((c) => c.type === "refactor"));
out += emit("Everything else", commits);
console.log(out.trimEnd());
')"

if [ -n "$COMPARE" ]; then
    HEADER="## [$TITLE]($COMPARE) - $DATE"
else
    HEADER="## $TITLE - $DATE"
fi

SECTION="$HEADER

$BODY"

# -- emit or write -------------------------------------------------------------

if [ "$WRITE" = 1 ]; then
    CHANGELOG="$REPO_ROOT/CHANGELOG.md"
    if [ -f "$CHANGELOG" ] && grep -qF "$HEADER" "$CHANGELOG"; then
        step "Section already present in CHANGELOG.md -- nothing to do"
        exit 0
    fi
    if [ -f "$CHANGELOG" ]; then
        H1="$(head -1 "$CHANGELOG")"
        REST="$(tail -n +2 "$CHANGELOG")"
    else
        H1="# Changelog"
        REST="All notable changes to this project are documented here.
Generated by tools/changelog.sh; entries follow conventional-commit types.
"
    fi
    printf '%s\n\n%s\n%s' "$H1" "$SECTION" "$REST" >"$CHANGELOG"
    step "CHANGELOG.md updated"
    note "$HEADER"
else
    printf '%s\n' "$SECTION"
fi